options:
  app_name:
    type: string
    default: myapp
    description: Application Name
  repo_url:
    type: string
    default: "http://github.com/mmm/testrails.git"
    description: Application repository URL
  repo_branch:
    type: string
    default: master
    description: Application repository deployment branch
  repo_type:
    type: string
    default: git
    description: Repository type (git/bzr/...)
  install_root:
    type: string
    default: /opt
    description: Install the application in app_name under this directory
